version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /tools/analysis-container
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /tools/sdk-container
    schedule:
      interval: weekly
